version: '3'

services:
  ## Traefik - HTTP reverse proxy and load balancer
  ## Docker Hub: https://hub.docker.com/_/traefik
  ## Docs: https://doc.traefik.io/traefik/
  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      # - "80:80"
      - "443:443"
      - "666:666"
    environment:
      DO_AUTH_TOKEN: ${TRAEFIK_DO_TOKEN}
      TZ: ${TZ}
    volumes:
      - "${CONFIG}/traefik/certificates:/letsencrypt:rw"
      - "${CONFIG}/traefik/config:/etc/traefik:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.traefik-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-rtr.service=api@internal
      - traefik.http.routers.traefik-rtr.middlewares=authelia@docker

networks:
  proxy:
    name: proxy
